version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - sqlserver
    environment:
      DB_SERVER: sqlserver
      DB_NAME: FavaDB
      DB_USER: sa
      DB_PASSWORD: 1qaz#EDC


volumes:
  sqlvolume:
